### ISSUE TITLE
🏆 Awesome and epic initiative from juliahartman

### ISSUE THREAD

**Issue by juliahartman** [juliahartman/Non-dev-training-14-03-2#10]
- [ ] 🎸 A feature from juliahartman that rocks
- [ ] ⚡ Another epic feature from juliahartman
- [ ] 🔥 Hot feature from juliahartman
